site_name: AutoFV_Framework

nav:
  - Home: index.md
  - Generate a Formal Framework: GenerateFramework.md
  - Generated Formal Files: GeneratedFiles.md
  - Run Formal: RunFormal.md
  - Property Macros Usage: PropertyMacros.md
  - AutoFV Software Architecture: SoftwareArchitecture.md
  - Contributing: Contributing.md
  - FAQ: FAQ.md


theme:
  name: readthedocs